name: release

permissions:
    contents: write
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Compile
        run: javac src/etsuko/*.java

      - name: Package into jar
        run: jar cfe game-of-life-java.jar etsuko.Main src/etsuko/*.class

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: game-of-life-java.jar
          tag_name: ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
            Commit ${{ github.sha }}
