name: release

permissions:
    contents: write
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Compile
        run: javac src/etsuko/*.java

      - name: Package into jar
        run: jar cfe game-of-life-java.jar etsuko.Main src/etsuko/*.class

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: game-of-life-java.jar
          tag: ${{ github.ref }}